### PR TITLE
Add jscs and jshint

### PR DESCRIPTION
**Pull request by nikolas**
To run locally:
  * `npm install`
  * `npm test`

They're configured to run automatically in travis. This is a preliminary step for #1324

### CODE REVIEW

**Comment by SimenB** [comment]
@nikolas `npm scripts` automatically adds `node_modules/.bin` to `$PATH`, you don't need to specify the path manually

**Comment by nikolas** [comment]
@SimenB The `npm scripts` is unrecognized for me, in npm version 2.7.6.

**Comment by SimenB** [comment]
I meant `scripts`-field in package.json.

**Comment by nikolas** [comment]
I still don't understand. If you show me an example of your proposed change, I can revise my PR.

**Comment by SimenB** [comment]
```json
 "scripts": {
    "pretest": "jscs . && jshint require.js"
  },
```

**Comment by nikolas** [comment]
Thanks! I just revised the commit.

**Comment by nikolas** [comment]
@jrburke do you have any input on this? I'd like to get automated testing working on requirejs so I can come up with a test case for a problem I'm seeing in the domReady plugin: https://github.com/requirejs/domReady/issues/13

I see this as the first step to that goal.

**Comment by jrburke** [comment]
This has been difficult for me to respond to because it combines a few assumptions in it:

1) That jscs in its "google" config form is the style this repo should use.
2) It makes sense to run automation on travis for this project.

Some more details:

1) I like code style checkers. require.js does have a style guide applied to it, but mostly enforced during reviews, or just applied as I do changes. The style I prefer now is the one that is closer to the one used for Mozilla/Gaia projects now, which is different than the style in this repo.

There are two choices that I see: 

a) customize the jscs config so that it matches closer to the style used in the file. It is fine if require.js needs some (less than 10?) changes to meet that style guide, but the current 152 is too high, indicates a disconnect between the tool and the convention in this repo.

b) do a larger code formatting change. In that case I would prefer to use the style closer to the Mozilla one (2 spaces for tabs being the most visible).

I am a bit torn on this: On the one hand I do not like how it changes a bunch of lines just for style, at the cost of diffing history for real changes. On the other hand, I like these sorts of automated checks for style. This was not a pressing concern for me, so it has been hard for me to make a decision here.

I use jshint locally in my editor for this repo, so totally fine with its inclusion here, and require.js passes today with no problems.

2) This repo does not have a high rate of change now, and the more important thing to watch over time is if all the browser releases continue to work. I do not believe Travis can help here, as I thought it was hard to run things like IE on there. A more expansive cross-browser/OS test solution seems more appropriate here.

jburke/almond does use travis (wired up by a contributor), and that one makes a bit more sense. almond is not dependent on specific browser pathways like require.js is, the tests are more of a validation of the internal almond logic. However, the failures that can show up there are often a problem with just travis/connections, or what versions of node and what npm dependencies work with it an on travis, versus catching real issues. So the signal to noise ratio is not as strong as I would like.

---

As to a test case for requirejs/domReady#13, just having a test that shows the failure would be enough, something that is standalone that does not require a smart server. Bonus points if it can be dropped in the tests folder.

How I handle changes now that may affect browsers is to load tests/index.html in web browsers on my desktop (some running in VMs) and run the tests that way. That gives me a good feeling that it works in real browsers, vs something like PhantomJS, which is nice for some basic JS-in-browsers sanity check, but bad for some the harder issues for a module loader, namely around attachEvent/addEventListener code branches.

---

For this specific pull request, I feel issue 2) is probably better discussed in #1324. I will post what I have about 2) in that ticket to keep all info for that discussion there. For a merge of this pull request, where it is just doing style checks, travis seems fine. At the very least, just being able to run the style checks from the command line is an improvement, even if travis is not used. In fact, we can probably just remove the travis file from this pull request until #1324 is sorted.

For 1) : the easy answer would be to just expand the jscs config to match the style here more. I like the idea of converting the file to the [Mozilla style](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style), but a quick search around, I do not see a pre-made Mozilla one to start from. So that is more of an effort. 

For now, if you want to update the config to match existing style, that would result in this getting merged sooner. For whichever route is taken, jscs should pass without any errors for the pull request to be merged.

Thanks for taking the time to look into this.

**Comment by SimenB** [comment]
@nikolas 

These changes makes it 12 violations

```json
{
  "preset": "google",
  "validateIndentation": 4,
  "disallowSpacesInAnonymousFunctionExpression": null,
  "disallowMultipleVarDecl": null,
  "maximumLineLength": {
    "value": 120,
    "allowComments": true,
    "allowRegex": true
  },
  "excludeFiles": [
    "dist/**",
    "node_modules/**",
    "tests/**"
  ]
}
```

So removing `disallowSpacesInAnonymousFunctionExpression` and `disallowMultipleVarDecl`, as well as allowing line length to be 120.

**Comment by SimenB** [comment]
@jrburke What are the rules from Mozilla? From what I could throw together it would be.

```json
{
    "validateIndentation": 2,
    "validateLineBreaks": "LF",
    "requireMultipleVarDecl": true,
    "requireLineFeedAtFileEnd": true
}
```

`requireMultipleVarDecl` is not mentioned in the JS styles, only in the Java one.
From what I could find in https://github.com/mozilla/togetherjs (top hit on google for mozilla javascript libs :laughing: ), there also seems to be `disallowQuotedKeysInObjects`, but that's not mentioned in the style guide. Mostly double-quotes, but a few single quotes here and there.

Basing a preset on a project and not the formal rules might be wrong as well...

**Comment by jrburke** [comment]
@SimenB: the main style guide is here:
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style

with the "General practices", "JavaScript practices", and "Naming and formatting code" sections being the most relevant. I do not think "requireMultipleVarDecl" is a hard and fast rule, at least it has not been on Gaia code, and I would prefer the option to have multiple declarations for requirejs. Maybe not specifying it means it is not checked for it (still new to jscs)?

The things that stick out most to me, that I would need to change in requirejs to get closer to Mozilla style would be:

* 2 spaces for tabs, and no tab characters
* Max 80 characters per line
* `function() {}` instead of `function () {}`

requirejs also uses a style of all var declarations at the top (old jslint style), where I think it would be fine to allow var definitions near to where they are used. But not enforcing that in style, I would just expect to move to that style over time if major changes were done.

Also making sure there is no trailing whitespace would be nice: requirejs does that now, would like to keep that formally specified.

**Comment by SimenB** [comment]
@jrburke Not specifying means not checking, yes :smile: 

Ah, didn't notice the Naming and formatting part. I must be half blind... A lot of rules comes out of that one.

OK, so 
```json
{
    "validateIndentation": 2,
    "validateLineBreaks": "LF",
    "disallowTrailingWhitespace": true,
    "requireLineFeedAtFileEnd": true,
    "maximumLineLength": 80,
    "disallowSpacesInFunctionDeclaration": {
        "beforeOpeningRoundBrace": true
    },
    "disallowKeywordsOnNewLine": ["else"],
    "requireAnonymousFunctions": true,
    "requireSpaceBeforeBlockStatements": true,
    "requireSpaceBeforeObjectValues": true,
    "requireSpacesInsideObjectBrackets": "all",
    "requireCapitalizedConstructors": true,
    "validateQuoteMarks": { "mark": "\"", "escape": true },
    "requireCurlyBraces": [
        "if",
        "else",
        "for",
        "while",
        "do",
        "try",
        "catch"
    ]
}
```

That's a more decent number... This is for a Mozilla preset, which would then be tweaked for e.g. this project.

**Comment by jrburke** [comment]
@SimenB thanks for doing that. Thinking more about it, how about for this ticket, let's focus on doing a first pass that just matches existing style as close as possible, and I can fix any straggling issues on the basic style you outlined in the comment that mentioned 12 violations. But please feel free to open a new ticket with the 2 space indentation version to move to after getting the basics in place.

**Pull request closed without merging**
