### PR TITLE
Add work-around for a worker GC bug in WebKit / Blink

### PR DESCRIPTION
**Pull request by Rob--W**
For more details and test cases, see https://crbug.com/572225 ("Web Worker garbage-collected after using importScripts").

### CODE REVIEW

**Comment by jrburke** [comment]
It looks like the source bug in chrome has been fixed, so I am closing out this pull request, prefer to have it fixed there anyway, more robust across other importScripts usage outside of requirejs.

**Comment by Rob--W** [comment]
I only submitted a patch to Blink, which fixes the bug in Chrome and Opera.
But other WebKit-based runtimes such as Safari, QtWebKit and other
WebKit-derivates are also affected, so it still makes much sense to merge
this small PR.

**Comment by Rob--W** [comment]
@jrburke Ping, please merge this PR, as there are still many runtimes where the bug is NOT fixed.

**Comment by jrburke** [comment]
Do you have a bug URL for the webkit case? It would be good to include it in the comment, as I will want to remove this workaround once the fixes are in and get some deployment. I'll look at merging if we can get the comment sorted out.

**Comment by Rob--W** [comment]
I've also reported the bug at WebKit: https://bugs.webkit.org/show_bug.cgi?id=153317, and updated the comment in the code and commit description.

My test case in the WebKit bug report is more general than the one in Chrome's issue tracker, you can use it in Chrome (48 and earlier) without any special flags to verify that the bug exists and that putting `setTimeout(function() {});` before `importScripts` fixes the bug.

**Comment by Rob--W** [comment]
Could you re-open the issue? Github doesn't automatically update the PR if a branch is updated while the PR is closed.

Here's a preview of the new commit: https://github.com/Rob--W/requirejs/commit/f55f190120d87239acadc2cbec91fc788d93f9a9

**Comment by jrburke** [comment]
Hmm, I cannot seem to reopen, says it is because the branch had a force push done to it or recreated. Sorry for the extra difficulty, I should have reopened it when I last commented. If it is not too much trouble, just open a new pull request.

**Comment by Rob--W** [comment]
I just force-pushed the old commit, can you try to re-open now?

**Comment by jrburke** [comment]
Reopened!

**Comment by Rob--W** [comment]
Thanks. I the new commit is now associated with this PR.

**Pull request merged**
