### PR TITLE
 Added missing API reference material

### PR DESCRIPTION
**Pull request by SetTrend**
Added config options TOC for easier reference.
Added *module ID* reference.
Added *require()* reference.
Added missing technical reference, neccessary to understand RequireJS.
Added samples.
Improved config options content.
Added a glimmer of didactic structure to the document.
Improved English wording.
Removed HTML errors / English typos.

### CODE REVIEW

**Comment by SetTrend** [comment]
I do have submitted a CLA.

**Comment by jrburke** [comment]
Thanks for taking the time to do a pull request. It looks like there are substantial formatting changes, perhaps it is just the usage of tabs vs 2 spaces instead of tabs, but the end result is that a diff cannot be generated by github to make inspection of the pull request easier.

Please reformat to return the document to the two space indentation, and for any new code samples match existing style in the doc, particularly the use of trailing commas instead of leading ones on the next line.

If editing on Windows, making sure a line returns stay as just \n instead of \r\n will be very helpful too.

**Comment by SetTrend** [comment]
Thank, JR, I'll amend the white spacing (although I won't be able to change the new-line formatting) and check in the update then.

Cheers,
Axel

**Comment by SetTrend** [comment]
I have now checked-in the new version with the new formating.

From what I can see GitHub still isn't able to compare. The GitHub file comparison seems to lack functionality here.

But it shouldn't be a problem to copy/paste both versions of the file to your local hard disk and compare them with a decent comparison tool, like Araxis Merge or Beyond Compare, like I did:

beyond compare

**Comment by SetTrend** [comment]
Let me share the GitHub support response I received today on this issue with you:

----------------------------------
Hi Axel,

As far as I can tell, the diff for that file is larger than 150K, which is more than that it's currently allowed, for performance reasons:

https://help.github.com/articles/what-are-the-limits-for-viewing-content-and-diffs-in-my-repository/#diff-limits

You can still fetch the raw diff here:

https://patch-diff.githubusercontent.com/raw/jrburke/requirejs/pull/1410.diff

Let me know if this doesn't explain the behavior you observed.

Best,
Ivan

----------------------------------

**Comment by jrburke** [comment]
Previewing the raw diff it looks like the bulk of the changes are the line return issues, shows every file as changed. I do not want to commit that sort of change to the repo, as it makes it hard to track individual changes when it looks like the whole file changed. I am not sure how to avoid the crlfs in the pull request though. It will likely take me a while to resolve this on my own, expect longer review time. If you find something that can fix the issue in the pull request though feel free to let me know.

**Comment by SetTrend** [comment]
I do have a plug-in available for my merge tool, Beyond Compare, which is unifying HTML files before comparison. Could you use the same for your comparison? The original file would be required to undergo the same unifying process so I can't do this on my side.

Here's the tool used by the Beyond Compare HTML comparison plug-in: [HTML Tidy](http://www.htacg.org/tidy-html5/)

**Comment by SetTrend** [comment]
Just want to make sure this is not getting lost. *ping*

**Comment by chrisknoll** [comment]
@SetTrend: he's not going to accept a pull request which is going to clutter the git history with hundreds of changes that were only made due to formatting changes. I think that the next step for you is to take your changes and apply them to a fresh pull request, but make sure you do not do any major format changes so only the changes you are making get captured in the pull request.

**Comment by SetTrend** [comment]
Ok, I understand. Actually the main changes have been valuable content that's been added.

I don't want to spend any more time on this. I've got my version - that's sufficient for me.

**Pull request closed without merging**
